FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY entrypoint.sh /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]

# Customizations
ARG JAR_FILE
ARG TOTAL_STATUSES
ENV TOTAL_STATUSES=${TOTAL_STATUSES}

ARG TIMEOUT_SECONDS
ENV TIMEOUT_SECONDS=${TIMEOUT_SECONDS}

ARG CONSUMER_KEY
ENV CONSUMER_KEY=${CONSUMER_KEY}

ARG CONSUMER_SECRET
ENV CONSUMER_SECRET=${CONSUMER_SECRET}

ADD target/${JAR_FILE} /app.jar